# Generated by Django 4.2.11 on 2024-03-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('ShipName', models.CharField(max_length=200)),
                ('ShipCurrentCaptain', models.CharField(max_length=100)),
                ('ShipEmail', models.CharField(max_length=100)),
                ('ShipMobile', models.CharField(max_length=100)),
                ('ShipOriginCOuntry', models.CharField(max_length=100)),
                ('ShipOriginPort', models.CharField(max_length=200)),
                ('ShipSize', models.CharField(max_length=100)),
                ('ShipTotalIncident', models.IntegerField(blank=True, null=True)),
                ('ShipLastServiceDate', models.DateField()),
                ('ShipCarbonEmission', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
