# Generated by Django 4.2.11 on 2024-03-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCRMApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiprecords',
            old_name='ShipOriginCOuntry',
            new_name='ShipOriginCountry',
        ),
    ]
